name: Migrate Secrets
on:   
  workflow_dispatch:
    inputs:
      targetRepo: 
        description: 'Environment (dev, stage, prod)'
        required: true
        
jobs:
  Migrate-Secrets:
    runs-on: ubuntu-latest
    steps:
    
      # Check out repository code
      - name: Check out repository code
        id: push_secrets
        uses: actions/checkout@main
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
        with:
          repository: 'jvsrikanth11/scrs-test-secrets-project'
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
        
      
      - run: |
            curl -X PUT -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" -H "Content-Type: application/json" -i https://api.github.com/repos/jvsrikanth11/scrs-test-secrets-project/actions/secrets/APP_KEY -d '{"key_id": "$APP_KEY", "encrypted_value": "$APP_KEY"}'
          
      - name: view the secrets context
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
