name: Migrate Secrets
on:   
  workflow_dispatch:
    inputs:
      targetRepo: 
        description: 'Environment (dev, stage, prod)'
        required: true
        
jobs:
  Migrate-Secrets:
    runs-on: ubuntu-latest
    steps:
    
      # Check out repository code
      - name: Check out repository code
        uses: actions/checkout@main
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      
      - name: fetch public_key
        id: fetch_public_key
        run: |
          fetch_public_key=$(curl --location --request GET 'https://api.github.com/repos/jvsrikanth11/scrs-configurer/actions/secrets/public-key' --header 'Authorization: token ${{ secrets.ACCESS_TOKEN }}')
          echo '::set-output name=public_key_response::$fetch_public_key'
      
      - run: echo "Response --> ${{ steps.fetch_public_key.outputs.public_key_response }}"
      
      - name: Make encryption script file executeable
        run: |
          pwd 
          sudo chmod +x ${{ github.workspace }}/.github/scripts/encrypt_secrets.py
          python ${{ github.workspace }}/.github/scripts/encrypt_secrets.py
          
