name: Migrate Secrets
on:   
  [push]
        
jobs:
  Migrate-Secrets:
    runs-on: ubuntu-latest
    steps:
    
      # Check out repository code
      - name: Check out repository code
        uses: actions/checkout@main
        with:
          secrets: ${{ secrets.APP_KEY }}
          repository: 'jvsrikanth11/scrs-test-secrets-project'
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
      
      
