name: Migrate Secrets
on:   
  workflow_dispatch:
    inputs:
      targetRepo: 
        description: 'Environment (dev, stage, prod)'
        required: true
jobs:
  Migrate-Secrets:
    runs-on: ubuntu-latest
    steps:
    
      # Check out repository code
      - name: Check out repository code
        id: push_secrets
        uses: actions/checkout@main
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
        with:
          repository: 'jvsrikanth11/scrs-test-secrets-project'
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - name: view the secrets context
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
