name: Migrate Secrets
on:   
  workflow_dispatch:
    inputs:
      targetRepo: 
        description: 'Environment (dev, stage, prod)'
        required: true
        
jobs:
  Migrate-Secrets:
    runs-on: ubuntu-latest
    steps:
    
      # Check out repository code
      - name: Check out repository code
        uses: actions/checkout@main
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      
      - name: fetch public_key
        run: |
          public_key_response= curl --location --request GET 'https://api.github.com/repos/jvsrikanth11/scrs-configurer/actions/secrets/public-key' --header 'Authorization: ${{ secrets.ACCESS_TOKEN }}'
          echo $public_key_response
          echo $public_key_response.public_key
      
      - name: Make encryption script file executeable
        run: chmod +x ./.github/scripts/encrypt_secrets.py        
      
      - name: execute py script # run the run.py to get the latest data
        run: |
          python ./.github/scripts/encrypt_secrets.py
